---
- hosts: all
  connection: ssh
  gather_facts: no
  tasks:
    - name: Upgrade all packages to the latest version
      yum:
        name: "*"
        state: latest
   -  name: Download the nginx package but do not install it
      yum:
        name: git
        state: latest
        download_only: true
