---
- hosts: all
  sudo: yes
  sudo_user: cloud_user
  become: true
  vars:
    version: 2.9.5
    prefix: /usr/local
    temp_dir: /tmp
    binary_dir: "{{ temp_dir }}/git-{{ 2.9.5 }}"
    url: "https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.9.5.tar.gz "
  tasks:
    - name: Install yum package
      yum:
        name:
          - curl-devel
          - expat-devel
          - gettext-devel
          - openssl-devel
          - zlib-devel
          - wget
          - gcc
          - cpan

    - name: Get git binary
      unarchive:
        src: "{{ url }}"
        dest: "{{ temp_dir }}"
        remote_src: yes
      changed_when: false
      register: result

    - name: Make all git binary
      make:
        chdir: "{{ binary_dir }}"
        target: all
        params:
          prefix: "{{ prefix }}"
      changed_when: false

    - name: Make install git binary
      make:
        chdir: "{{ binary_dir }}"
        target: install
        params:
          prefix: "{{ prefix }}"
