
---
- hosts: all
  tasks:
    - name: Install apache httpd  (state=present is optional)
      yum:
       name: apache2
       state: present

    - name: Upgrade all packages to the latest version
      yum:
       name: "*"
       state: latest
    - name: Install apache httpd  (state=present is optional)
      yum:
       name: git
       state: present
