
---
- hosts: all
  tasks:
    - name: install the latest version of Apache
      yum:
        name: httpd
        state: latest

   - name: ensure a list of packages installed
     yum:
       name: "{{ packages }}"
       vars:
       packages:
            - httpd
            - httpd-tools
