-- # play example
- hosts: all
  become: yes
  tasks:
    - name: install software
      yum:
        name: elinks
        state: latest
    - name: install more software
      yum:
        name: Notepad++
        state: latest

