---
- hosts: all
  user: server1-123
  # sudo: yes
  become: yes
  tasks:
    - name: install software
      yum:
        name: elinks
        state: latest
    - name: install more software
      yum:
        name: Notepad++
        state: latest

