---
- hosts: all
  connection: ssh
  #remote_user: server1-123
  gather_facts: no
  tasks:
    - name: Transfer the script
      copy: src=/home/admin123/ansible/Playbooks/test.txt dest=/home/server1-123/test.txt

      



