---
- hosts: all
  tasks:
    - name: upgrade all packages 
      yum:
         name: '*'
         state: latest
         
    - name: Download the nginx package but do not install it
      yum:
        name:
         - nginx
        state: latest
        download_only: true
   
