---
- hosts: all
 # become: true
  connection: ssh
  gather_facts: yes
  tasks:
     - name: user name
       shell: whoami
   # - name: Upgrade all packages to the latest version
   #   yum:
   #    name: "*"
   #    state: latest
       
    - name: install the latest version of Apache
      yum:
       name: httpd
       state: latest
       
    - name: install the latest version of git
      yum:
       name: git
       state: latest
       
    - name: install the latest version of zip
      yum:
       name: zip
       state: latest
